// ============================================================
// Samsic Planning IA - Seed Data
// Realistic Luxembourg demo data (French names, local context)
//
// IMPORTANT: All date-dependent data is generated by factory functions
// (generateSeedAbsences, generateSeedAffectations, generateSeedAlerts)
// so that every cold start in serverless produces dates relative to
// the *current* day, not the day the module was first imported.
// ============================================================

import type {
  Employee,
  Client,
  Affectation,
  Absence,
  Alert,
} from './types';

// --- Date helpers (called at generation time, never cached) ---

function today(): string {
  return new Date().toISOString().split('T')[0];
}

function weekday(offsetFromMonday: number): string {
  const now = new Date();
  const dayOfWeek = now.getDay(); // 0=Sun, 1=Mon...
  const monday = new Date(now);
  monday.setDate(now.getDate() - (dayOfWeek === 0 ? 6 : dayOfWeek - 1));
  const target = new Date(monday);
  target.setDate(monday.getDate() + offsetFromMonday);
  return target.toISOString().split('T')[0];
}

/** Returns the day-of-week offset (0=Mon ... 4=Fri) for today, clamped to weekdays. */
function todayWeekdayOffset(): number {
  const dow = new Date().getDay(); // 0=Sun, 1=Mon ... 6=Sat
  if (dow === 0) return 4; // Sunday -> treat as Friday for demo
  if (dow === 6) return 4; // Saturday -> treat as Friday for demo
  return dow - 1; // Mon=0, Tue=1 ... Fri=4
}

// ============================================================
// EMPLOYEES (15)
// Static data -- no dates that need to be dynamic.
// ============================================================

export const seedEmployees: Employee[] = [
  {
    id: 'emp-001',
    nom: 'Schmit',
    prenom: 'Marie',
    email: 'marie.schmit@samsic.lu',
    telephone: '+352 621 100 001',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 40,
    langues: [
      { language: 'FR', level: 'natif' },
      { language: 'LU', level: 'courant' },
      { language: 'DE', level: 'intermediaire' },
      { language: 'EN', level: 'courant' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'microsoft_office' },
      { skill: 'gestion_courrier' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2024-03-15', date_expiry: '2026-03-15', is_valid: true },
      { name: 'RGPD', date_obtained: '2025-01-10', date_expiry: '2027-01-10', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 36,
    created_at: '2023-03-01T08:00:00Z',
  },
  {
    id: 'emp-002',
    nom: 'Ferreira',
    prenom: 'Ana',
    email: 'ana.ferreira@samsic.lu',
    telephone: '+352 621 100 002',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 40,
    langues: [
      { language: 'FR', level: 'courant' },
      { language: 'PT', level: 'natif' },
      { language: 'EN', level: 'intermediaire' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'prise_rdv' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2024-06-20', date_expiry: '2026-06-20', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 24,
    created_at: '2024-03-01T08:00:00Z',
  },
  {
    id: 'emp-003',
    nom: 'Weber',
    prenom: 'Julie',
    email: 'julie.weber@samsic.lu',
    telephone: '+352 621 100 003',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 40,
    langues: [
      { language: 'FR', level: 'natif' },
      { language: 'LU', level: 'natif' },
      { language: 'DE', level: 'courant' },
      { language: 'EN', level: 'courant' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'microsoft_office' },
      { skill: 'facturation' },
      { skill: 'gestion_courrier' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2023-09-01', date_expiry: '2025-09-01', is_valid: true },
      { name: 'RGPD', date_obtained: '2024-05-15', date_expiry: '2026-05-15', is_valid: true },
      { name: 'Sécurité Incendie', date_obtained: '2024-01-20', date_expiry: '2026-01-20', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 48,
    created_at: '2022-03-01T08:00:00Z',
  },
  {
    id: 'emp-004',
    nom: 'Muller',
    prenom: 'Sophie',
    email: 'sophie.muller@samsic.lu',
    telephone: '+352 621 100 004',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 40,
    langues: [
      { language: 'FR', level: 'natif' },
      { language: 'DE', level: 'natif' },
      { language: 'EN', level: 'courant' },
      { language: 'LU', level: 'intermediaire' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'microsoft_office' },
      { skill: 'accueil_juridique' },
      { skill: 'prise_rdv' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2024-02-01', date_expiry: '2026-02-01', is_valid: true },
      { name: 'RGPD', date_obtained: '2024-02-01', date_expiry: '2026-02-01', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 30,
    created_at: '2023-09-01T08:00:00Z',
  },
  {
    id: 'emp-005',
    nom: 'Thill',
    prenom: 'Chantal',
    email: 'chantal.thill@samsic.lu',
    telephone: '+352 621 100 005',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 40,
    langues: [
      { language: 'FR', level: 'natif' },
      { language: 'LU', level: 'courant' },
      { language: 'EN', level: 'intermediaire' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'gestion_courrier' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2025-01-15', date_expiry: '2027-01-15', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 18,
    created_at: '2024-09-01T08:00:00Z',
  },
  {
    id: 'emp-006',
    nom: 'Da Silva',
    prenom: 'Carlos',
    email: 'carlos.dasilva@samsic.lu',
    telephone: '+352 621 100 006',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 40,
    langues: [
      { language: 'FR', level: 'courant' },
      { language: 'PT', level: 'natif' },
      { language: 'EN', level: 'notions' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2024-11-01', date_expiry: '2026-11-01', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 12,
    created_at: '2025-03-01T08:00:00Z',
  },
  {
    id: 'emp-007',
    nom: 'Klein',
    prenom: 'Nathalie',
    email: 'nathalie.klein@samsic.lu',
    telephone: '+352 621 100 007',
    type_contrat: 'CDD',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 16, // Only 2 formation days this week
    langues: [
      { language: 'FR', level: 'natif' },
      { language: 'DE', level: 'courant' },
      { language: 'EN', level: 'courant' },
      { language: 'LU', level: 'notions' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'microsoft_office' },
      { skill: 'prise_rdv' },
      { skill: 'facturation' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2025-06-01', date_expiry: '2027-06-01', is_valid: true },
      { name: 'RGPD', date_obtained: '2025-06-01', date_expiry: '2027-06-01', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 9,
    created_at: '2025-06-01T08:00:00Z',
  },
  {
    id: 'emp-008',
    nom: 'Reuter',
    prenom: 'Isabelle',
    email: 'isabelle.reuter@samsic.lu',
    telephone: '+352 621 100 008',
    type_contrat: 'CDI',
    temps_travail: 'mi_temps',
    heures_hebdo: 20,
    heures_planifiees_semaine: 20,
    langues: [
      { language: 'FR', level: 'natif' },
      { language: 'LU', level: 'courant' },
      { language: 'DE', level: 'intermediaire' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'gestion_courrier' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2024-08-01', date_expiry: '2026-08-01', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 20,
    created_at: '2024-07-01T08:00:00Z',
  },
  {
    id: 'emp-009',
    nom: 'Hoffmann',
    prenom: 'Laura',
    email: 'laura.hoffmann@samsic.lu',
    telephone: '+352 621 100 009',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 40,
    langues: [
      { language: 'FR', level: 'courant' },
      { language: 'DE', level: 'natif' },
      { language: 'EN', level: 'courant' },
      { language: 'LU', level: 'courant' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'microsoft_office' },
      { skill: 'accueil_juridique' },
      { skill: 'prise_rdv' },
      { skill: 'facturation' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2023-05-01', date_expiry: '2025-05-01', is_valid: false },
      { name: 'RGPD', date_obtained: '2024-03-01', date_expiry: '2026-03-01', is_valid: true },
      { name: 'Sécurité Incendie', date_obtained: '2024-03-01', date_expiry: '2026-03-01', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 42,
    created_at: '2022-09-01T08:00:00Z',
  },
  {
    id: 'emp-010',
    nom: 'Pinto',
    prenom: 'Sandra',
    email: 'sandra.pinto@samsic.lu',
    telephone: '+352 621 100 010',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 32,
    langues: [
      { language: 'FR', level: 'courant' },
      { language: 'PT', level: 'natif' },
      { language: 'EN', level: 'courant' },
      { language: 'DE', level: 'notions' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'microsoft_office' },
      { skill: 'prise_rdv' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2025-02-01', date_expiry: '2027-02-01', is_valid: true },
      { name: 'RGPD', date_obtained: '2025-02-01', date_expiry: '2027-02-01', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 15,
    created_at: '2024-12-01T08:00:00Z',
  },
  {
    id: 'emp-011',
    nom: 'Becker',
    prenom: 'Christine',
    email: 'christine.becker@samsic.lu',
    telephone: '+352 621 100 011',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 0,
    langues: [
      { language: 'FR', level: 'natif' },
      { language: 'LU', level: 'natif' },
      { language: 'DE', level: 'courant' },
      { language: 'EN', level: 'intermediaire' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'microsoft_office' },
      { skill: 'gestion_courrier' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2025-09-01', date_expiry: '2027-09-01', is_valid: true },
      { name: 'RGPD', date_obtained: '2025-09-01', date_expiry: '2027-09-01', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 6,
    created_at: '2025-09-01T08:00:00Z',
  },
  {
    id: 'emp-012',
    nom: 'Lentz',
    prenom: 'Marc',
    email: 'marc.lentz@samsic.lu',
    telephone: '+352 621 100 012',
    type_contrat: 'interim',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 0,
    langues: [
      { language: 'FR', level: 'natif' },
      { language: 'EN', level: 'courant' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2026-01-10', date_expiry: '2028-01-10', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 2,
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'emp-013',
    nom: 'Schiltz',
    prenom: 'Diane',
    email: 'diane.schiltz@samsic.lu',
    telephone: '+352 621 100 013',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 40,
    langues: [
      { language: 'FR', level: 'natif' },
      { language: 'LU', level: 'natif' },
      { language: 'DE', level: 'natif' },
      { language: 'EN', level: 'courant' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'microsoft_office' },
      { skill: 'accueil_juridique' },
      { skill: 'prise_rdv' },
      { skill: 'gestion_courrier' },
      { skill: 'facturation' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2024-01-01', date_expiry: '2026-01-01', is_valid: true },
      { name: 'RGPD', date_obtained: '2024-01-01', date_expiry: '2026-01-01', is_valid: true },
      { name: 'Sécurité Incendie', date_obtained: '2024-06-01', date_expiry: '2026-06-01', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 60,
    created_at: '2021-03-01T08:00:00Z',
  },
  {
    id: 'emp-014',
    nom: 'Rodrigues',
    prenom: 'Lucia',
    email: 'lucia.rodrigues@samsic.lu',
    telephone: '+352 621 100 014',
    type_contrat: 'CDD',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 8, // Only 1 formation day this week
    langues: [
      { language: 'FR', level: 'courant' },
      { language: 'PT', level: 'natif' },
      { language: 'EN', level: 'intermediaire' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'prise_rdv' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2025-10-01', date_expiry: '2027-10-01', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 5,
    created_at: '2025-10-01T08:00:00Z',
  },
  {
    id: 'emp-015',
    nom: 'Wagner',
    prenom: 'Thomas',
    email: 'thomas.wagner@samsic.lu',
    telephone: '+352 621 100 015',
    type_contrat: 'CDI',
    temps_travail: 'temps_plein',
    heures_hebdo: 40,
    heures_planifiees_semaine: 40,
    langues: [
      { language: 'FR', level: 'courant' },
      { language: 'DE', level: 'natif' },
      { language: 'LU', level: 'courant' },
      { language: 'EN', level: 'courant' },
    ],
    competences: [
      { skill: 'accueil_standard' },
      { skill: 'gestion_appels' },
      { skill: 'microsoft_office' },
      { skill: 'gestion_courrier' },
      { skill: 'facturation' },
    ],
    formations: [
      { name: 'Accueil & Sécurité', date_obtained: '2024-04-01', date_expiry: '2026-04-01', is_valid: true },
      { name: 'RGPD', date_obtained: '2024-04-01', date_expiry: '2026-04-01', is_valid: true },
    ],
    statut: 'actif',
    anciennete_mois: 28,
    created_at: '2023-11-01T08:00:00Z',
  },
];

// ============================================================
// CLIENTS (6 sites)
// Static data -- employee lists are logical:
//   - Each client has 1 titulaire (primary receptionist)
//   - en_formation: employees being trained for this site
//   - stand_by: designated backup employees
//   - No employee is titulaire at more than one client
// ============================================================

export const seedClients: Client[] = [
  {
    id: 'cli-001',
    nom: 'Banque Fortuna',
    adresse: '12 Boulevard Royal, L-2449 Luxembourg',
    horaire_debut: '08:00',
    horaire_fin: '17:30',
    langues_requises: [
      { language: 'FR', minimum_level: 'courant' },
      { language: 'EN', minimum_level: 'courant' },
      { language: 'DE', minimum_level: 'intermediaire' },
    ],
    competences_requises: ['accueil_standard', 'gestion_appels', 'microsoft_office', 'facturation'],
    priorite: 'haute',
    certifications_requises: ['RGPD'],
    titulaires: ['emp-003'],
    en_formation: ['emp-007'],
    stand_by: ['emp-011'],
  },
  {
    id: 'cli-002',
    nom: 'Cabinet Albers & Associés',
    adresse: '45 Avenue de la Liberté, L-1931 Luxembourg',
    horaire_debut: '08:30',
    horaire_fin: '18:00',
    langues_requises: [
      { language: 'FR', minimum_level: 'natif' },
      { language: 'DE', minimum_level: 'courant' },
      { language: 'EN', minimum_level: 'courant' },
    ],
    competences_requises: ['accueil_standard', 'gestion_appels', 'accueil_juridique', 'prise_rdv'],
    priorite: 'haute',
    certifications_requises: ['RGPD'],
    titulaires: ['emp-004'],
    en_formation: [],
    stand_by: ['emp-013'],
  },
  {
    id: 'cli-003',
    nom: 'Hôtel Le Royal',
    adresse: '12 Boulevard Royal, L-2449 Luxembourg',
    horaire_debut: '07:00',
    horaire_fin: '15:00',
    langues_requises: [
      { language: 'FR', minimum_level: 'courant' },
      { language: 'EN', minimum_level: 'courant' },
    ],
    competences_requises: ['accueil_standard', 'gestion_appels', 'prise_rdv'],
    priorite: 'haute',
    certifications_requises: [],
    titulaires: ['emp-001'],
    en_formation: ['emp-014'],
    stand_by: ['emp-010'],
  },
  {
    id: 'cli-004',
    nom: 'Assurances Foyer',
    adresse: '12 Rue Léon Laval, L-3372 Leudelange',
    horaire_debut: '08:00',
    horaire_fin: '17:00',
    langues_requises: [
      { language: 'FR', minimum_level: 'courant' },
      { language: 'LU', minimum_level: 'intermediaire' },
    ],
    competences_requises: ['accueil_standard', 'gestion_appels', 'gestion_courrier'],
    priorite: 'moyenne',
    certifications_requises: [],
    titulaires: ['emp-005'],
    en_formation: [],
    stand_by: ['emp-008'],
  },
  {
    id: 'cli-005',
    nom: 'Ministère des Finances',
    adresse: '3 Rue de la Congrégation, L-1352 Luxembourg',
    horaire_debut: '07:30',
    horaire_fin: '16:30',
    langues_requises: [
      { language: 'FR', minimum_level: 'natif' },
      { language: 'LU', minimum_level: 'courant' },
      { language: 'DE', minimum_level: 'courant' },
    ],
    competences_requises: ['accueil_standard', 'gestion_appels', 'microsoft_office', 'gestion_courrier'],
    priorite: 'haute',
    certifications_requises: ['Sécurité Incendie'],
    titulaires: ['emp-013'],
    en_formation: ['emp-015'],
    stand_by: ['emp-009'],
  },
  {
    id: 'cli-006',
    nom: 'Clinique Bohler',
    adresse: '5 Rue Edward Steichen, L-2540 Luxembourg',
    horaire_debut: '07:00',
    horaire_fin: '19:00',
    langues_requises: [
      { language: 'FR', minimum_level: 'courant' },
      { language: 'EN', minimum_level: 'intermediaire' },
    ],
    competences_requises: ['accueil_standard', 'gestion_appels', 'prise_rdv', 'microsoft_office'],
    priorite: 'haute',
    certifications_requises: [],
    titulaires: ['emp-009'],
    en_formation: ['emp-002'],
    stand_by: ['emp-012'],
  },
];

// ============================================================
// AFFECTATIONS (current week) - generated dynamically
//
// Story: Each titulaire is assigned Mon-Fri at their client.
// Formation and stand_by assignments fill out the week.
// ============================================================

export function generateSeedAffectations(): Affectation[] {
  const todayOffset = todayWeekdayOffset();

  // Titulaire assignments: each of the 6 clients' titulaire works Mon-Fri
  const titulairePairs: [string, string][] = [
    ['emp-003', 'cli-001'], // Julie Weber -> Banque Fortuna
    ['emp-004', 'cli-002'], // Sophie Muller -> Cabinet Albers
    ['emp-001', 'cli-003'], // Marie Schmit -> Hotel Le Royal
    ['emp-005', 'cli-004'], // Chantal Thill -> Assurances Foyer
    ['emp-013', 'cli-005'], // Diane Schiltz -> Ministere des Finances
    ['emp-009', 'cli-006'], // Laura Hoffmann -> Clinique Bohler
  ];

  const affectations: Affectation[] = [];

  for (const [empId, clientId] of titulairePairs) {
    for (let day = 0; day < 5; day++) {
      affectations.push({
        id: `aff-${clientId.replace('cli-', '')}-${day + 1}`,
        employe_id: empId,
        client_id: clientId,
        date: weekday(day),
        type: 'titulaire',
        statut: 'confirme',
        created_at: '2026-03-01T08:00:00Z',
      });
    }
  }

  // Formation: emp-007 (Nathalie Klein) training at Banque Fortuna Mon+Tue
  affectations.push(
    {
      id: 'aff-form-001',
      employe_id: 'emp-007',
      client_id: 'cli-001',
      date: weekday(0),
      type: 'formation',
      statut: 'confirme',
      created_at: '2026-03-01T08:00:00Z',
    },
    {
      id: 'aff-form-002',
      employe_id: 'emp-007',
      client_id: 'cli-001',
      date: weekday(1),
      type: 'formation',
      statut: 'confirme',
      created_at: '2026-03-01T08:00:00Z',
    },
  );

  // Formation: emp-014 (Lucia Rodrigues) training at Hotel Le Royal on Wednesday
  affectations.push({
    id: 'aff-form-003',
    employe_id: 'emp-014',
    client_id: 'cli-003',
    date: weekday(2),
    type: 'formation',
    statut: 'confirme',
    created_at: '2026-03-01T08:00:00Z',
  });

  // Formation: emp-002 (Ana Ferreira) training at Clinique Bohler on Thursday
  affectations.push({
    id: 'aff-form-004',
    employe_id: 'emp-002',
    client_id: 'cli-006',
    date: weekday(3),
    type: 'formation',
    statut: 'confirme',
    created_at: '2026-03-01T08:00:00Z',
  });

  // Formation: emp-015 (Thomas Wagner) training at Ministere on Tuesday
  affectations.push({
    id: 'aff-form-005',
    employe_id: 'emp-015',
    client_id: 'cli-005',
    date: weekday(1),
    type: 'formation',
    statut: 'confirme',
    created_at: '2026-03-01T08:00:00Z',
  });

  // Stand-by: emp-006 (Carlos) covers Assurances Foyer on Wednesday
  affectations.push({
    id: 'aff-sb-001',
    employe_id: 'emp-006',
    client_id: 'cli-004',
    date: weekday(2),
    type: 'stand_by',
    statut: 'confirme',
    created_at: '2026-03-01T08:00:00Z',
  });

  // Stand-by: emp-010 (Sandra) covers Hotel Le Royal on Friday
  affectations.push({
    id: 'aff-sb-002',
    employe_id: 'emp-010',
    client_id: 'cli-003',
    date: weekday(4),
    type: 'stand_by',
    statut: 'confirme',
    created_at: '2026-03-01T08:00:00Z',
  });

  return affectations;
}

// ============================================================
// ABSENCES - generated dynamically so "today" is always current
//
// Story for the demo:
// 1. Julie Weber (titulaire Banque Fortuna) is sick today -> urgent, uncovered
// 2. Sophie Muller (titulaire Cabinet Albers) has an unplanned absence today -> urgent, uncovered
// 3. Diane Schiltz (titulaire Min. Finances) has a planned leave on Thursday -> upcoming, uncovered
// This gives the dashboard 2 absences today (both uncovered) + 1 upcoming.
// ============================================================

export function generateSeedAbsences(): Absence[] {
  const todayStr = today();
  const nowIso = new Date().toISOString();

  return [
    {
      id: 'abs-001',
      employe_id: 'emp-003',
      client_id: 'cli-001',
      date: todayStr,
      type: 'maladie',
      channel: 'telephone',
      statut: 'ouverte',
      notes: 'Grippe, certificat médical à fournir sous 48h.',
      created_at: nowIso,
    },
    {
      id: 'abs-002',
      employe_id: 'emp-004',
      client_id: 'cli-002',
      date: todayStr,
      type: 'imprevue',
      channel: 'whatsapp',
      statut: 'ouverte',
      notes: 'Problème familial urgent, absence signalée à 7h15 ce matin.',
      created_at: nowIso,
    },
    {
      id: 'abs-003',
      employe_id: 'emp-013',
      client_id: 'cli-005',
      date: weekday(3), // Thursday
      type: 'conge',
      channel: 'email',
      statut: 'ouverte',
      notes: 'Congé personnel validé par la direction.',
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];
}

// ============================================================
// ALERTS - generated dynamically
// ============================================================

export function generateSeedAlerts(): Alert[] {
  const nowIso = new Date().toISOString();

  return [
    {
      id: 'alert-001',
      type: 'absence',
      priority: 'urgent',
      title: 'Absence maladie - Banque Fortuna',
      description: 'Julie Weber (titulaire) est absente aujourd\'hui pour maladie. Le poste n\'est pas encore couvert.',
      related_client_id: 'cli-001',
      related_employe_id: 'emp-003',
      is_read: false,
      action_url: '/absences/abs-001',
      created_at: nowIso,
    },
    {
      id: 'alert-002',
      type: 'poste_non_couvert',
      priority: 'urgent',
      title: 'Poste non couvert - Banque Fortuna',
      description: 'Le poste accueil Banque Fortuna n\'a pas de remplacement confirmé pour aujourd\'hui.',
      related_client_id: 'cli-001',
      is_read: false,
      action_url: '/planning',
      created_at: nowIso,
    },
    {
      id: 'alert-003',
      type: 'absence',
      priority: 'urgent',
      title: 'Absence imprévue - Cabinet Albers',
      description: 'Sophie Muller (titulaire) est absente aujourd\'hui pour raison personnelle. Remplacement urgent requis.',
      related_client_id: 'cli-002',
      related_employe_id: 'emp-004',
      is_read: false,
      action_url: '/absences/abs-002',
      created_at: nowIso,
    },
    {
      id: 'alert-004',
      type: 'poste_non_couvert',
      priority: 'urgent',
      title: 'Poste non couvert - Cabinet Albers',
      description: 'Le poste accueil Cabinet Albers & Associés n\'a pas de remplacement confirmé pour aujourd\'hui.',
      related_client_id: 'cli-002',
      is_read: false,
      action_url: '/planning',
      created_at: nowIso,
    },
    {
      id: 'alert-005',
      type: 'absence',
      priority: 'moyen',
      title: 'Congé planifié - Min. Finances',
      description: 'Diane Schiltz sera en congé jeudi. Remplacement à organiser pour le Ministère des Finances.',
      related_client_id: 'cli-005',
      related_employe_id: 'emp-013',
      is_read: false,
      action_url: '/absences/abs-003',
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'alert-006',
      type: 'formation_expiree',
      priority: 'moyen',
      title: 'Formation expirée - Laura Hoffmann',
      description: 'La certification "Accueil & Sécurité" de Laura Hoffmann a expiré le 01/05/2025. Renouvellement requis.',
      related_employe_id: 'emp-009',
      is_read: false,
      action_url: '/employes/emp-009',
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'alert-007',
      type: 'standby_insuffisant',
      priority: 'info',
      title: 'Stand-by insuffisant - Cabinet Albers',
      description: 'Le Cabinet Albers & Associés n\'a qu\'un seul employé en stand-by. Il est recommandé d\'en avoir au moins 2.',
      related_client_id: 'cli-002',
      is_read: true,
      action_url: '/clients/cli-002',
      created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'alert-008',
      type: 'refresh',
      priority: 'info',
      title: 'Rappel formation - 3 employés',
      description: '3 employés ont des formations qui expireront dans les 90 prochains jours.',
      is_read: true,
      action_url: '/employes',
      created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];
}
